/* Generated By:JavaCC: Do not edit this line. ASTGenConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASTGenConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENT = 20;
  /** RegularExpression Id. */
  int START = 21;
  /** RegularExpression Id. */
  int PART = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"abstract\"",
    "\"class\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 18>",
    "<token of kind 19>",
    "<IDENT>",
    "<START>",
    "<PART>",
  };

}
