package syntax;

import compiler.Handler;

/** Represents a public (i.e., accessible outside package) version
 *  of the MainParser class.  This wrapper is needed because the
 *  parsers generated by jacc are not public, so they cannot be
 *  accessed from outside the package in which they are defined.
 */
public class MiniParser extends MainParser {
    public MiniParser(Handler handler, MiniLexer lexer) {
      super(handler, lexer);
    }
}
