/* Generated By:JavaCC: Do not edit this line. ASTGenConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASTGenConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 18;
  /** RegularExpression Id. */
  int ABSTRACT = 19;
  /** RegularExpression Id. */
  int IDENT = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"protected\"",
    "\"private\"",
    "\"public\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 16>",
    "<token of kind 17>",
    "\"class\"",
    "\"abstract\"",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
  };

}
